use crate::page_allocator::PageAllocator;
use crate::util::{MAX_ALIGN, MAX_BLOCK_SIZE, MIN_ALIGN, MIN_BLOCK_SIZE};
use core::alloc::{AllocError, Layout};
use core::ops::Deref;
use core::ptr::NonNull;

/// A structure represented a pointer to a header which represents a single block of memory
// NOTE u8 is just a placehoelder, it just needs to be a pointer
pub trait InlineHeader
where
    Self: From<NonNull<Self::Header>> + Deref<Target = NonNull<Self::Header>> + Clone + Copy,
{
    type Header;

    unsafe fn new<T: ?Sized>(ptr: *mut T) -> Self;

    /// Gets the offset of the memory in the block represented by this header
    fn get_offset(&self) -> usize;
    /// Sets the offset of the memory in the block represented by this header
    fn set_offset(&mut self, offset: usize);

    /// Returns whether the block is currently used or free for use
    fn used(&self) -> bool;
    /// Sets whether the block is currently used or free for use
    fn set_used(&mut self, used: bool);

    /// Sets the block as free
    fn mark_free(&mut self) {
        self.set_used(false);
    }
    /// Sets the block as used
    fn mark_used(&mut self) {
        self.set_used(true);
    }

    /// Gets the size of the block, not including the offset
    fn size(&self) -> usize;
    /// Sets the size of the block, not including the offset
    fn set_size(&mut self, size: usize);
    /// Increments the size of the block, not including the offset
    fn add_size(&mut self, size: usize);

    /// Sets the value of the header pointer, not the header this struct points to
    fn set(&mut self, size: Self);

    // /// Sets the value of the pointer
    // pub fn set(&mut self, ptr: &HeaderPtr);

    /// Gets the underlying block represented by the header
    #[inline]
    fn get_data(&self) -> NonNull<u8> {
        let offset = self.get_offset();
        let header = Self::header_size();
        let base = self.addr().get();

        unsafe { NonNull::new_unchecked((base + header + offset) as *mut u8) }
    }
    /// Gets the last address in the block represented by this header
    /// Autogenerated because every block is assumed to be `size_of::<Header>() + offset` away from
    /// the header pointer
    // TODO This might need to be not autogenerated if we want to allow weirder things
    #[inline]
    fn last_addr(&self) -> usize {
        usize::from(self.addr()) + Self::header_size() + self.get_offset() + self.size()
    }

    /// Gets the next header
    #[must_use]
    unsafe fn next_unchecked(&self) -> Self;

    /// Merges two consecutive memory blocks in the buffer
    /// self and `prev_header` must point to contiguous blocks in memory
    fn merge_block(&mut self, prev_header: &mut Self, required_size: usize, align: usize) -> bool;

    /// Attempts to split the allocated block represented
    /// by `header`, into two blocks, the first one of size `new_size`
    ///
    /// Does nothing if there isn't enough space to split the block
    /// Or if `new_size > header.size() + size_of::<Header>()`
    fn try_split_allocated_block(&mut self, new_size: usize, last_addr: usize);
    fn can_split_allocated_block(&self, new_size: usize, last_addr: usize) -> bool;

    /// Allocates a new buffer of size `size` using the given `page_allocator`
    /// then writes a base header to it the buffer
    /// The header will represent the entire allocated buffer
    /// and so will be of size `page_allocator.get_page_size()`
    /// # Returns
    /// A pointer to the buffer containing the new header
    /// # Errors
    /// - If a buffer can't be allocated to store the header
    fn initialize_header(
        page_allocator: impl PageAllocator,
    ) -> Result<*mut Self::Header, AllocError>;

    /// Returns whether a given layout is valid to by represented by a header of this type
    /// For example, the layout size plus the header size may exceed the maximum layout size specificed by Yerba
    #[inline]
    #[must_use]
    fn is_valid_layout(layout: &Layout) -> bool {
        let align = layout.align();
        let size = layout.size();

        (MIN_ALIGN..=MAX_ALIGN).contains(&align)
            && size >= MIN_BLOCK_SIZE
            && size + Self::header_size() <= MAX_BLOCK_SIZE
    }

    #[must_use]
    fn header_size() -> usize {
        size_of::<Self::Header>()
    }
}
